import logging
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

from fastapi import APIRouter, BackgroundTasks, Depends, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.db.database import SessionLocal, get_db
from app.db.models import Claim, DecisionRecord, Policy, PolicyClause
from app.schemas.adjuster_schema import AdjusterDashboardResponse, AdjusterDashboardSummary, DecisionRead, DecisionRequest
from app.schemas.claim_schema import ClaimListResponse, ClaimRead
from app.services.analytics_service import AnalyticsService
from app.services.claim_analysis_graph import ClaimAnalysisOrchestrator
from app.services.claim_service import ClaimService
from app.services.investigation_service import InvestigationService

router = APIRouter(prefix='/claims', tags=['claims'])
logger = logging.getLogger("claims_portal.claims")

# Built once at import time (not per request) so the YOLO model, the
# sentence-transformer embeddings, and each policy's TF-IDF index are loaded
# once and reused, rather than reloaded on every claim submission.
_orchestrator = ClaimAnalysisOrchestrator()


def _sync_policy_clauses(db: Session, policy: Policy | None, claim: Claim | None, policy_findings: list[dict]) -> None:
    """Records the real, RAG-retrieved clauses a claim's analysis actually
    cited into the policy_clauses SQL table, one row per (claim, clause)
    citation -- so it reflects real ingested policy text (queryable via
    plain SQL and traceable back to the claim that used it) instead of
    staying disconnected from the ChromaDB-backed retrieval
    PolicyClauseService uses. The same clause is routinely cited by many
    claims, so uniqueness is scoped to claim+clause, not clause alone."""
    if policy is None or claim is None:
        return
    for finding in policy_findings or []:
        clause_id = finding.get("clause_id")
        if not clause_id or clause_id == "POLICY-LIMIT-CHECK":
            continue
        exists = db.query(PolicyClause).filter(
            PolicyClause.clause_id == clause_id,
            PolicyClause.claim_id == claim.id,
        ).first()
        if exists:
            continue
        db.add(PolicyClause(
            policy_id=policy.id,
            claim_id=claim.id,
            clause_id=clause_id,
            text=finding.get("text") or "",
            clause_metadata={
                "source_citation": finding.get("source_citation"),
                "clause_type": finding.get("clause_type"),
                "damage_class": finding.get("damage_class"),
                "score": finding.get("score"),
                "retrieval_breakdown": finding.get("retrieval_breakdown"),
            },
        ))


def run_claim_analysis(claim_id: str) -> None:
    """Runs the AI pipeline outside the request/response cycle (FR-010):
    claim submission must not block on YOLO/RAG/LLM latency. Opens its own
    DB session because the request-scoped session from Depends(get_db) is
    already closed by the time a FastAPI BackgroundTask runs."""
    db = SessionLocal()
    try:
        claim = ClaimService(db).get_claim(claim_id)
        claim.status = 'under review'
        db.commit()
        try:
            analysis_result = _orchestrator.run(claim, claim.policy)
        except Exception:
            logger.exception("AI analysis failed for claim %s", claim_id)
            claim.analysis_result.status = 'failed'
            db.commit()
            return
        claim.analysis_result.status = 'completed'
        claim.analysis_result.severity_label = analysis_result['severity_summary'].get('overall_severity')
        claim.analysis_result.severity_score = Decimal(str(analysis_result['severity_summary'].get('severity_score', 0)))
        claim.analysis_result.detections = analysis_result['detections']
        claim.analysis_result.policy_findings = analysis_result['policy_findings']
        claim.analysis_result.recommendation = analysis_result['report_json'].get('recommendation')
        claim.analysis_result.confidence_score = Decimal(str(analysis_result['report_json'].get('confidence_score', 0)))
        claim.analysis_result.fraud_score = Decimal(str((analysis_result.get('fraud_assessment') or {}).get('fraud_score', 0)))
        claim.analysis_result.explanation = 'Structured report generated by the AI pipeline.'
        report_json = analysis_result['report_json']
        report_json['fraud_assessment'] = analysis_result.get('fraud_assessment') or {}
        claim.analysis_result.report_json = report_json
        claim.analysis_result.needs_human_review = analysis_result['needs_human_review']
        claim.analysis_result.completed_at = datetime.utcnow()
        db.add(claim.analysis_result)

        _sync_policy_clauses(db, claim.policy, claim, analysis_result['policy_findings'])

        photos = claim.photos or []
        detections = analysis_result.get('detections') or []
        if photos and detections:
            primary_photo = photos[0]
            annotated_path = _orchestrator.damage_service.annotate_image(primary_photo.file_path, detections)
            if annotated_path:
                primary_photo.annotated_path = annotated_path
                db.add(primary_photo)

        db.commit()
    finally:
        db.close()

@router.post('', response_model=ClaimRead, status_code=201)
async def create_claim(
    request: Request,
    background_tasks: BackgroundTasks,
    policy_number: str | None = Form(default=None),
    claimant_name: str | None = Form(default=None),
    contact_info: str | None = Form(default=None),
    incident_date: date | None = Form(default=None),
    incident_description: str | None = Form(default=None),
    claimed_amount: Decimal | None = Form(default=None),
    photos: list[UploadFile] = File(default=[]),
    db: Session = Depends(get_db),
):
    if request.headers.get("content-type", "").startswith("application/json"):
        payload = await request.json()
        policy_number = payload["policy_number"]
        claimant_name = payload["claimant_name"]
        contact_info = payload["contact_info"]
        incident_date = date.fromisoformat(payload["incident_date"])
        incident_description = payload["incident_description"]
        claimed_amount = Decimal(str(payload["claimed_amount"]))
        photos = []

    if not all([policy_number, claimant_name, contact_info, incident_date, incident_description, claimed_amount]):
        raise HTTPException(status_code=422, detail="Missing required claim fields")

    if len(photos) < 1 or len(photos) > 5:
        if request.headers.get("content-type", "").startswith("application/json"):
            photos = []
        else:
            raise HTTPException(status_code=422, detail='Upload between 1 and 5 photos')
    claim = await ClaimService(db).create_claim(
        policy_number,
        claimant_name,
        contact_info,
        incident_date,
        incident_description,
        claimed_amount,
        photos,
    )
    background_tasks.add_task(run_claim_analysis, claim.claim_id)
    return claim

@router.get('/adjuster-dashboard', response_model=AdjusterDashboardResponse)
def adjuster_dashboard(db: Session = Depends(get_db)):
    claims = ClaimService(db).list_claims(['submitted', 'under review'])
    summary = AdjusterDashboardSummary(
        pending_count=len(claims),
        approved_count=db.query(DecisionRecord).filter(DecisionRecord.decision == 'approved').count(),
        denied_count=db.query(DecisionRecord).filter(DecisionRecord.decision == 'denied').count(),
    )
    return {
        'summary': summary,
        'claims': [
            {
                'claim_id': claim.claim_id,
                'claimant_name': claim.claimant_name,
                'status': claim.status,
                'claimed_amount': str(claim.claimed_amount),
            }
            for claim in claims
        ],
    }

SIU_FRAUD_THRESHOLD = Decimal('0.65')


@router.get('/siu-dashboard')
def siu_dashboard(db: Session = Depends(get_db)):
    claims = ClaimService(db).list_claims(['submitted', 'under review'])
    investigations = InvestigationService(db)
    cases = []
    for claim in claims:
        if claim.analysis_result and claim.analysis_result.fraud_score and claim.analysis_result.fraud_score >= SIU_FRAUD_THRESHOLD:
            case = investigations.get_case(claim.claim_id)
            cases.append({
                'claim_id': claim.claim_id,
                'claimant_name': claim.claimant_name,
                'claim_type': claim.incident_description,
                'claimed_amount': str(claim.claimed_amount),
                'fraud_score': str(claim.analysis_result.fraud_score),
                'needs_human_review': bool(claim.analysis_result.needs_human_review),
                'investigation_status': case.status if case else 'not_started',
            })
    under_investigation_count = sum(1 for c in cases if c['investigation_status'] == 'under_investigation')
    confirmed_fraud_count = sum(1 for c in cases if c['investigation_status'] == 'confirmed_fraud')
    return {
        'summary': {
            'high_risk_count': len(cases),
            'under_investigation_count': under_investigation_count,
            'confirmed_fraud_count': confirmed_fraud_count,
        },
        'claims': cases,
    }

@router.get('/{claim_id}', response_model=ClaimRead)
def get_claim(claim_id: str, db: Session = Depends(get_db)):
    return ClaimService(db).get_claim(claim_id)

@router.get('/{claim_id}/annotated-photo')
def get_annotated_photo(claim_id: str, db: Session = Depends(get_db)):
    """Returns the claim's primary uploaded photo with the damage-detection
    model's bounding boxes drawn on it, so an adjuster can see what the
    model predicted without leaving the dashboard. Falls back to the raw
    photo if detections aren't available yet (analysis still pending)."""
    claim = ClaimService(db).get_claim(claim_id)
    photos = claim.photos or []
    if not photos:
        raise HTTPException(status_code=404, detail='No photo uploaded for this claim')
    photo = photos[0]
    source_path = Path(photo.file_path)
    if not source_path.exists():
        raise HTTPException(status_code=404, detail='Photo file is missing on disk')

    if photo.annotated_path and Path(photo.annotated_path).exists():
        return FileResponse(photo.annotated_path, media_type='image/jpeg')

    detections = claim.analysis_result.detections if claim.analysis_result else None
    if detections:
        annotated_path = _orchestrator.damage_service.annotate_image(source_path, detections)
        if annotated_path and Path(annotated_path).exists():
            photo.annotated_path = annotated_path
            db.add(photo)
            db.commit()
            return FileResponse(annotated_path, media_type='image/jpeg')
    return FileResponse(source_path, media_type=photo.mime_type or 'image/jpeg')

@router.get('/{claim_id}/detail')
def get_claim_detail(claim_id: str, db: Session = Depends(get_db)):
    claim = ClaimService(db).get_claim(claim_id)
    if claim.analysis_result is None:
        return {
            'claim_id': claim.claim_id,
            'status': claim.status,
            'analysis_result': {'status': 'pending'},
        }
    return {
        'claim_id': claim.claim_id,
        'status': claim.status,
        'analysis_result': {
            'status': claim.analysis_result.status,
            'severity_label': claim.analysis_result.severity_label,
            'severity_score': str(claim.analysis_result.severity_score) if claim.analysis_result.severity_score is not None else None,
            'detections': claim.analysis_result.detections,
            'policy_findings': claim.analysis_result.policy_findings,
            'recommendation': claim.analysis_result.recommendation,
            'confidence_score': str(claim.analysis_result.confidence_score) if claim.analysis_result.confidence_score is not None else None,
            'explanation': claim.analysis_result.explanation,
            'fraud_score': str(claim.analysis_result.fraud_score) if claim.analysis_result.fraud_score is not None else None,
            'report_json': claim.analysis_result.report_json,
            'needs_human_review': claim.analysis_result.needs_human_review,
        },
    }

DECISION_TO_STATUS = {
    'approved': 'approved',
    'denied': 'denied',
    'request_more_info': 'under review',
}


@router.post('/{claim_id}/decision', response_model=DecisionRead)
def submit_decision(claim_id: str, payload: DecisionRequest, db: Session = Depends(get_db)):
    claim = ClaimService(db).get_claim(claim_id)
    record = claim.decision_record or DecisionRecord(claim=claim)
    record.decision = payload.decision
    record.reasoning_note = payload.reasoning_note
    record.settlement_amount = payload.settlement_amount
    db.add(record)
    claim.status = DECISION_TO_STATUS.get(payload.decision, claim.status)
    db.commit()
    db.refresh(record)
    return record

@router.get('', response_model=ClaimListResponse)
def list_claims(status: str | None = None, db: Session = Depends(get_db)):
    return {'claims': ClaimService(db).list_claims(status)}

@router.post('/{claim_id}/siu-action')
def siu_action(claim_id: str, payload: dict, db: Session = Depends(get_db)):
    claim = ClaimService(db).get_claim(claim_id)
    service = InvestigationService(db)
    case = service.upsert_case(claim, investigator_id=payload.get('investigator_id'), status=payload.get('status', 'under_investigation'), notes=payload.get('notes'))
    return {'claim_id': claim.claim_id, 'status': case.status}
